// packages/web-qwik/src/components/common/tag.tsx
import { component$, CSSProperties } from "@builder.io/qwik";

import styles from "./tag.module.css";
import { ElmInlineIcon, ElmInlineText } from "@elmethis/qwik";

export interface TagProps {
  style?: CSSProperties;
  name: string;
  src: string;
}

export const Tag = component$<TagProps>(({ name, src, style }) => {
  return (
    <span class={styles["tag"]} style={style}>
      <ElmInlineIcon src={src} alt={`Icon of ${name}`} />
      <ElmInlineText style={{ whiteSpace: "nowrap" }}>{name}</ElmInlineText>
    </span>
  );
});

// packages/web-solid/src/components/common/tag.tsx
import type { JSX } from "solid-js";

import styles from "./tag.module.css";
import { ElmInlineIcon, ElmInlineText } from "@elmethis/solid";

export interface TagProps {
  style?: JSX.CSSProperties;
  name: string;
  src: string;
}

export function Tag(props: TagProps) {
  return (
    <span class={styles["tag"]} style={props.style}>
      <ElmInlineIcon src={props.src} alt={`Icon of ${props.name}`} />
      <ElmInlineText style={{ "white-space": "nowrap" }}>
        {props.name}
      </ElmInlineText>
    </span>
  );
}
