// packages/web-qwik/src/routes/privacy/index.tsx
import { component$ } from "@qwik.dev/core";
import { DocumentHead } from "@qwik.dev/router";
import { Privacy } from "~/components/main/privacy";
import { generateHead } from "~/utils/common";

export default component$(() => {
  return <Privacy language="en" />;
});

export const head: DocumentHead = ({ url }) => {
  const headBase = generateHead({
    url: url.toString(),
    title: "Privacy Policy",
    ogType: "profile",
    description: "Personal blog and portfolio",
    language: "en",
  });

  return headBase;
};

// packages/web-solid/src/routes/[[lang]]/privacy.tsx
import { useLocation } from "@solidjs/router";

import { Seo } from "~/components/common/seo";
import { Privacy } from "~/components/main/privacy";
import { useI18n } from "~/i18n/context";
import type { Locale } from "~/i18n/locale";

const metadata: Record<Locale, { title: string; description: string }> = {
  en: { title: "Privacy Policy", description: "Portfolio and blog" },
  ja: {
    title: "プライバシーポリシー",
    description: "ポートフォリオとブログ",
  },
};

export default function PrivacyRoute() {
  const location = useLocation();
  const { locale } = useI18n();
  const meta = () => metadata[locale()];

  return (
    <>
      <Seo
        title={meta().title}
        description={meta().description}
        locale={locale()}
        pathname={location.pathname}
        type="website"
      />
      <Privacy />
    </>
  );
}
