// packages/web-qwik/src/components/common/header.tsx
import { component$, useContext } from "@builder.io/qwik";

import styles from "./header.module.scss";

import Favicon from "../../../public/static/brand/logo.svg?jsx";
import { ElmInlineText, ElmMdiIcon, ElmToggleTheme } from "@elmethis/qwik";
import { Language } from "./language";
import { LinkLocale } from "./link-locale";
import {
  mdiAccount,
  mdiAccountVoice,
  mdiNoteOutline,
  mdiOpenInNew,
} from "@mdi/js";
import { LanguageContext } from "~/context/language";

export const Header = component$(() => {
  const languageState = useContext(LanguageContext);

  return (
    <header class={styles.header}>
      <div class={styles["header-left"]}>
        <LinkLocale href="/" class={styles.link} lang={languageState.language}>
          <Favicon style={{ height: "1.5rem", width: "min-content" }} />
        </LinkLocale>
      </div>

      <div class={styles["header-center"]}>
        <LinkLocale
          href="/about"
          class={styles.link}
          lang={languageState.language}
        >
          <ElmMdiIcon d={mdiAccount} />
          <ElmInlineText>About</ElmInlineText>
        </LinkLocale>

        <ElmInlineText>|</ElmInlineText>

        <LinkLocale
          href="/blog"
          class={styles.link}
          lang={languageState.language}
        >
          <ElmMdiIcon d={mdiNoteOutline} />
          <ElmInlineText>Blog</ElmInlineText>
        </LinkLocale>

        <ElmInlineText>|</ElmInlineText>

        <a
          href="https://speakerdeck.com/ikuma"
          class={styles.link}
          target="_blank"
          rel="noopener noreferrer"
        >
          <ElmMdiIcon d={mdiAccountVoice} />
          <ElmInlineText>Speaker Deck</ElmInlineText>
          <ElmMdiIcon d={mdiOpenInNew} />
        </a>
      </div>

      <div class={styles["header-right"]}>
        <Language />
        <ElmToggleTheme />
      </div>
    </header>
  );
});

// packages/web/components/base/Header.vue
<template>
  <header class="header">
    <div class="header-left flex-center">
      <NuxtLinkLocale to="/" class="logo">
        <img alt="Logo" src="/static/brand/logo.svg" class="logo-image" />
      </NuxtLinkLocale>
    </div>

    <ClientOnly>
      <div v-if="isMobile" class="header-center flex-center">
        <NuxtLinkLocale to="/about" class="header-center-link flex-center">
          <Icon
            class="header-center-link-icon"
            icon="ix:user-profile-filled"
            width="16px"
          />
          <ElmInlineText text="About" />
        </NuxtLinkLocale>

        <Icon
          class="header-center-link-icon"
          icon="ci:line-l"
          width="16px"
          color="gray"
        />

        <NuxtLinkLocale to="/blog" class="header-center-link flex-center">
          <Icon
            class="header-center-link-icon"
            icon="material-symbols:article"
            width="16px"
          />
          <ElmInlineText text="Blog" />
        </NuxtLinkLocale>

        <Icon
          class="header-center-link-icon"
          icon="ci:line-l"
          width="16px"
          color="gray"
        />

        <a
          href="https://speakerdeck.com/ikuma"
          class="header-center-link flex-center"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Icon
            class="header-center-link-icon"
            icon="mdi:account-voice"
            width="16px"
          />
          <ElmInlineText text="Talks" />
          <Icon
            class="header-center-link-icon"
            icon="mdi:open-in-new"
            width="12px"
          />
        </a>
      </div>
    </ClientOnly>

    <div class="header-right flex-center">
      <BaseLanguage />

      <ElmToggleTheme />
    </div>
  </header>
</template>

<script setup lang="ts">
import { ElmInlineText, ElmToggleTheme } from "@elmethis/vue";
import { Icon } from "@iconify/vue";
import { useMediaQuery } from "@vueuse/core";

const isMobile = useMediaQuery("(min-width: 1024px)");
</script>

<style lang="scss" scoped>
@use "../../styles/variables";

.header {
  position: sticky;
  top: 0;
  z-index: 10;
  box-sizing: border-box;
  padding: 0.5rem 0;
  height: #{variables.$header-height};
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  backdrop-filter: blur(1px);
  box-shadow: 0 0 0.125rem rgb(black, 0.2);
  background-color: rgb(white, 0.3);

  [data-theme="dark"] & {
    background-color: rgb(black, 0.3);
  }
}

.flex-center {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  gap: 0.5rem;
}

.header-left {
  margin-left: 0.5rem;
}

.header-center {
  user-select: none;
  gap: 0.25rem;
}

.header-center-link {
  text-decoration: none;
  padding: 0.25rem;
  border-radius: 0.25rem;
  opacity: 0.6;
  transition: opacity 150ms;
  cursor: pointer;

  &:hover {
    opacity: 1;
  }
}

.header-center-link-icon {
  color: rgb(black, 0.8);

  [data-theme="dark"] & {
    color: rgb(white, 0.8);
  }
}

.header-right {
  margin-right: 0.5rem;
}

.logo {
  padding: 0.5rem 0.25rem;
  border-radius: 0.25rem;
  height: 1.5rem;
  transition: opacity 200ms;

  &:hover {
    opacity: 0.6;
  }
}

.logo-image {
  height: 100%;
}
</style>
