// packages/web-solid/src/components/blog/blog-search.tsx
import {
  ElmButton,
  ElmCollapse,
  ElmHeading,
  ElmMdiIcon,
  ElmTextField,
} from "@elmethis/solid";
import { createAutoAnimate } from "@formkit/auto-animate/solid";
import { mdiTagRemove } from "@mdi/js";
import { useNavigate } from "@solidjs/router";
import Fuse from "fuse.js";
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  onCleanup,
  Show,
} from "solid-js";

import { Meta } from "../common/meta";
import { Tag } from "../common/tag";
import { useBlog } from "~/context/blog";
import { useI18n } from "~/i18n/context";
import { BlogCard } from "./blog-card";

import styles from "./blog-search.module.css";

export function BlogSearch() {
  const blogState = useBlog();
  const { t, locale, localizePath } = useI18n();
  const navigate = useNavigate();
  const [selectedTagsAnimation] = createAutoAnimate<HTMLDivElement>();
  const [resultsAnimation] = createAutoAnimate<HTMLDivElement>();
  const [searchKeyword, setSearchKeyword] = createSignal("");
  const [debouncedKeyword, setDebouncedKeyword] = createSignal("");

  const fuse = createMemo(
    () =>
      new Fuse(blogState.blogMeta, {
        keys: [
          { name: "title", weight: 0.7 },
          { name: "description", weight: 0.3 },
          { name: "keywords", weight: 1 },
        ],
        threshold: 0.3,
      }),
  );

  let searchTimer: ReturnType<typeof setTimeout> | undefined;
  createEffect(() => {
    const keyword = searchKeyword();
    clearTimeout(searchTimer);
    searchTimer = setTimeout(() => setDebouncedKeyword(keyword), 300);
  });
  onCleanup(() => clearTimeout(searchTimer));

  const searchResults = createMemo(() => {
    const keyword = debouncedKeyword().trim();
    const matches = keyword
      ? fuse()
          .search(keyword, { limit: 10 })
          .map((result) => result.item)
      : blogState.blogMeta;

    return matches.filter((blog) =>
      blogState.selectedTagIds().every((tagId) => blog.tag_ids.includes(tagId)),
    );
  });

  const visibleResults = createMemo(() =>
    searchKeyword().trim() === "" && blogState.selectedTagIds().length === 0
      ? blogState.blogMeta
      : searchResults(),
  );

  const addTag = (tagId: string) => {
    if (!blogState.selectedTagIds().includes(tagId)) {
      blogState.setSelectedTagIds((current) => [...current, tagId]);
    }
  };
  const removeTag = (tagId: string) =>
    blogState.setSelectedTagIds((current) =>
      current.filter((id) => id !== tagId),
    );

  return (
    <>
      <Meta
        title="Blog Search"
        createdAt="2026-03-05"
        updatedAt="2026-03-05"
        links={[
          {
            text: t("common.home"),
            onClick: () => navigate(localizePath("/")),
          },
          {
            text: t("common.blog"),
            onClick: () => navigate(localizePath("/blog")),
          },
          {
            text: t("common.search"),
            onClick: () => navigate(localizePath("/blog/search")),
          },
        ]}
      />
      <div class={styles["blog-search"]}>
        <div style={{ "margin-block": "2rem" }}>
          <ElmTextField
            value={searchKeyword()}
            label="Keyword"
            onInput={(event) => setSearchKeyword(event.currentTarget.value)}
          />
        </div>
        <ElmHeading level={2}>{t("common.tags")}</ElmHeading>
        <div class={styles["tag-pool"]}>
          <For each={blogState.tags}>
            {(tag) => (
              <span
                class={`${styles["tag-wrapper"]} ${styles.add}`}
                onClick={() => addTag(tag.id)}
              >
                <Tag
                  name={locale() === "en" ? tag.name_en : tag.name_ja}
                  src={tag.icon_url ?? ""}
                  style={{
                    "view-transition-name": `blog-search-tag-pool-${tag.id}`,
                  }}
                />
              </span>
            )}
          </For>
        </div>
        <ElmHeading level={2}>{t("common.selectedTags")}</ElmHeading>
        <ElmCollapse isOpen={blogState.selectedTagIds().length > 0}>
          <div
            ref={selectedTagsAnimation}
            class={styles["tag-pool"]}
            classList={{
              [styles.empty]: blogState.selectedTagIds().length === 0,
            }}
          >
            <For each={blogState.selectedTagIds()}>
              {(tagId) => {
                const tag = () =>
                  blogState.tags.find((candidate) => candidate.id === tagId);
                return (
                  <Show when={tag()} keyed>
                    {(selectedTag) => (
                      <span
                        class={`${styles["tag-wrapper"]} ${styles.remove}`}
                        onClick={() => removeTag(selectedTag.id)}
                      >
                        <Tag
                          name={
                            locale() === "en"
                              ? selectedTag.name_en
                              : selectedTag.name_ja
                          }
                          src={selectedTag.icon_url ?? ""}
                          style={{
                            "view-transition-name": `blog-search-tag-selected-${selectedTag.id}`,
                          }}
                        />
                      </span>
                    )}
                  </Show>
                );
              }}
            </For>
          </div>
        </ElmCollapse>
        <div style={{ "margin-block": "1rem" }}>
          <ElmButton
            type="button"
            onClick={() => blogState.setSelectedTagIds([])}
            block
          >
            <ElmMdiIcon class={styles.icon} path={mdiTagRemove} />
            {t("common.resetTags")}
          </ElmButton>
        </div>
        <ElmHeading level={2}>{t("common.searchResults")}</ElmHeading>
        <div ref={resultsAnimation} class={styles["blog-search-result"]}>
          <For each={visibleResults()}>
            {(blog) => (
              <BlogCard
                blog={blog}
                tags={blogState.tags.filter((tag) =>
                  blog.tag_ids.includes(tag.id),
                )}
                style={{
                  "view-transition-name": `blog-search-blog-card-${blog.page_id}`,
                }}
              />
            )}
          </For>
        </div>
      </div>
    </>
  );
}

// packages/web-qwik/src/components/blog/blog-search.tsx
import {
  $,
  component$,
  noSerialize,
  NoSerialize,
  useContext,
  useSignal,
} from "@builder.io/qwik";

import styles from "./blog-search.module.css";
import { BlogContext } from "~/context/blog";

import Fuse from "fuse.js";
import {
  ElmButton,
  ElmHeading,
  ElmInlineText,
  ElmMdiIcon,
  ElmTextField,
} from "@elmethis/qwik";
import { Language } from "~/types";
import { BlogCard } from "./blog-card";
import { Tag } from "../common/tag";
import { mdiTagRemove } from "@mdi/js";
import { Meta } from "../common/meta";
import { useNavigate } from "@builder.io/qwik-city";

import { delay } from "es-toolkit";

export type BlogSearchProps = {
  language: Language;
};

const translations = {
  en: {
    tags: "Tags",
    selectedTags: "Selected Tags",
    searchResults: "Search Results",
    resetTags: "Reset Tags",
  },
  ja: {
    tags: "タグ",
    selectedTags: "選択中のタグ",
    searchResults: "検索結果",
    resetTags: "タグ選択をリセット",
  },
};

export const BlogSearch = component$<BlogSearchProps>(({ language }) => {
  const nav = useNavigate();
  const blogState = useContext(BlogContext);

  const searchKeyword = useSignal("");
  const searchResults = useSignal<(typeof blogState.blogMeta)[Language]>([]);
  const fuseInstance = useSignal<NoSerialize<
    Fuse<(typeof blogState.blogMeta)[Language][number]>
  > | null>(null);

  const executeSearch = $(() => {
    if (fuseInstance.value == null) {
      fuseInstance.value = noSerialize(
        new Fuse(blogState.blogMeta[language], {
          keys: [
            { name: "title", weight: 0.7 },
            { name: "description", weight: 0.3 },
            { name: "keywords", weight: 1 },
          ],
          threshold: 0.3,
        }),
      );
    }

    if (fuseInstance.value != null) {
      const fuseSearchResults =
        searchKeyword.value.trim() === ""
          ? blogState.blogMeta[language]
          : fuseInstance.value
              .search(searchKeyword.value, {
                limit: 10,
              })
              .map(({ item }) => item);

      const results =
        fuseSearchResults.filter((blog) =>
          blogState.selectedTagIds.every((tagId) =>
            blog.tag_ids?.includes(tagId),
          ),
        ) ?? [];

      searchResults.value = results;
    } else {
      searchResults.value = [];
    }
  });

  const handleTagAdd = $((tagId: string) => {
    if (!blogState.selectedTagIds.includes(tagId)) {
      document.startViewTransition(async () => {
        blogState.selectedTagIds = [...blogState.selectedTagIds, tagId];
        await delay(0);
      });
    }
  });

  const handleTagRemove = $((tagId: string) => {
    document.startViewTransition(async () => {
      blogState.selectedTagIds = blogState.selectedTagIds.filter(
        (id) => id !== tagId,
      );
      await delay(0);
    });
  });

  const handleTagReset = $(() => {
    document.startViewTransition(async () => {
      blogState.selectedTagIds = [];
      await delay(0);
    });
  });

  const handleSearchKeywordChange = $((value: string) => {
    document.startViewTransition(async () => {
      searchKeyword.value = value;
      executeSearch();
      await delay(0);
    });
  });

  return (
    <>
      <Meta
        title="Blog Search"
        createdAt="2026-03-05"
        updatedAt="2026-03-05"
        links={[
          {
            text: "Home",
            onClick$: $(() => nav(language === "en" ? "/" : `/${language}`)),
          },
          {
            text: "Blog",
            onClick$: $(() =>
              nav(language === "en" ? "/blog" : `/${language}/blog`),
            ),
          },
          {
            text: "Search",
            onClick$: $(() =>
              nav(
                language === "en" ? "/blog/search" : `/${language}/blog/search`,
              ),
            ),
          },
        ]}
      />

      <div class={styles["blog-search"]}>
        <div style={{ marginBlock: "2rem" }}>
          <ElmTextField
            value={searchKeyword.value}
            onValueChange$={handleSearchKeywordChange}
            label="Keyword"
            icon="search"
          />
        </div>

        <ElmHeading level={2}>{translations[language].tags}</ElmHeading>

        <div class={styles["tag-pool"]}>
          {blogState.tags.map((tag) => (
            <span
              key={tag.id}
              class={[styles["tag-wrapper"], styles["add"]]}
              onClick$={() => handleTagAdd(tag.id)}
            >
              <Tag
                name={language === "en" ? tag.name_en : tag.name_ja}
                src={tag.icon_url!}
                style={{
                  viewTransitionName: `blog-search-tag-pool-${tag.id}`,
                }}
              />
            </span>
          ))}
        </div>

        <ElmHeading level={2}>{translations[language].selectedTags}</ElmHeading>

        <div
          class={[
            styles["tag-pool"],
            {
              [styles["empty"]]: blogState.selectedTagIds.length === 0,
            },
          ]}
        >
          {blogState.selectedTagIds.map((tagId) => {
            const tag = blogState.tags.find((t) => t.id === tagId);
            if (tag == null) return null;

            return (
              <span
                key={tag.id}
                class={[styles["tag-wrapper"], styles["remove"]]}
                onClick$={() => handleTagRemove(tag.id)}
              >
                <Tag
                  name={language === "en" ? tag.name_en : tag.name_ja}
                  src={tag.icon_url!}
                  style={{
                    viewTransitionName: `blog-search-tag-selected-${tag.id}`,
                  }}
                />
              </span>
            );
          })}
        </div>

        <div style={{ marginBlock: "2rem" }}>
          <ElmButton onClick$={handleTagReset} block>
            <ElmMdiIcon d={mdiTagRemove} />
            <ElmInlineText>{translations[language].resetTags}</ElmInlineText>
          </ElmButton>
        </div>

        <ElmHeading level={2}>
          {translations[language].searchResults}
        </ElmHeading>

        <div class={styles["blog-search-result"]}>
          {(searchResults.value.length > 0
            ? searchResults.value
            : blogState.blogMeta[language]
          ).map((blog) => (
            <BlogCard
              key={blog.slug}
              blog={blog}
              tags={blogState.tags?.filter((tag) =>
                blog.tag_ids?.includes(tag.id),
              )}
              language={language}
              style={{
                viewTransitionName: `blog-search-blog-card-${blog.page_id}`,
              }}
            />
          ))}
        </div>
      </div>
    </>
  );
});
