// packages/web-qwik/src/components/blog/blog-main.tsx
import { component$, Slot } from "@builder.io/qwik";

import styles from "./blog-main.module.css";
import { BlogAuthor } from "./blog-author";
import type { Language } from "~/types";

export type BlogMainProps = {
  language: Language;
};

export const BlogMain = component$<BlogMainProps>(({ language }) => {
  return (
    <main class={styles["blog-main"]}>
      <Slot />

      <BlogAuthor language={language} />
    </main>
  );
});

// packages/web-solid/src/components/blog/blog-main.tsx
import { ElmBlockFallback } from "@elmethis/solid";
import { Suspense, type ParentProps } from "solid-js";

import styles from "./blog-main.module.css";
import { BlogAuthor } from "./blog-author";

export function BlogMain(props: ParentProps) {
  return (
    <main class={styles["blog-main"]}>
      <Suspense fallback={<ElmBlockFallback height="calc(100vh - 8rem)" />}>
        {props.children}
      </Suspense>
      <BlogAuthor />
    </main>
  );
}
