// packages/web-qwik/src/components/common/date.tsx
import { component$ } from "@qwik.dev/core";

import styles from "./date.module.scss";
import { ElmInlineText, ElmMdiIcon } from "@elmethis/qwik";
import { mdiCalendarClock, mdiCalendarEdit } from "@mdi/js";

export interface DateProps {
  createdAt: string;
  updatedAt: string;
}

export const DateComponent = component$<DateProps>(
  ({ createdAt, updatedAt }) => {
    return (
      <div class={styles.date}>
        <ElmMdiIcon class={styles.icon} d={mdiCalendarEdit} size="1rem" />
        <ElmInlineText size="0.85rem">
          {createdAt.substring(0, 10)}
        </ElmInlineText>
        <ElmMdiIcon class={styles.icon} d={mdiCalendarClock} size="1rem" />
        <ElmInlineText size="0.85rem">
          {updatedAt.substring(0, 10)}
        </ElmInlineText>
      </div>
    );
  },
);

// packages/web/components/blog/Date.vue
<template>
  <div class="date">
    <Icon icon="mdi:calendar-month" class="icon" />
    <ElmInlineText :text="createdAt.substring(0, 10)" size="0.8rem" />
    <Icon icon="mdi:calendar-refresh" class="icon" />
    <ElmInlineText :text="updatedAt.substring(0, 10)" size="0.8rem" />
  </div>
</template>

<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { ElmInlineText } from "@elmethis/core";

interface BlogDateProps {
  createdAt: string;
  updatedAt: string;
}

defineProps<BlogDateProps>();
</script>

<style lang="scss" scoped>
.date {
  opacity: 0.7;
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  align-items: center;
  gap: 0.25rem;
}

.icon {
  color: rgba(black, 0.9);
  [data-theme="dark"] & {
    color: rgba(white, 0.9);
  }
}
</style>
