// packages/web-qwik/src/components/blog/blog-side.tsx
/* eslint-disable qwik/jsx-img */
import { component$, useContext, useStylesScoped$ } from "@builder.io/qwik";

import styles from "./blog-side.scoped.scss?inline";

import { ElmInlineText } from "@elmethis/qwik";
import { Link } from "@builder.io/qwik-city";
import { Date } from "../common/date";
import { BlogContext } from "~/context/blog";

export type BlogSideProps = {
  language: string;
};

export const BlogSide = component$<BlogSideProps>(({ language }) => {
  useStylesScoped$(styles);

  const blogState = useContext(BlogContext);

  return (
    <nav class="blog-side">
      <>
        {blogState.blogMeta?.map((blog) => (
          <Link
            key={blog.page_id}
            href={
              language === "en"
                ? `/blog/article/${blog.slug}`
                : `/${language}/blog/article/${blog.slug}`
            }
            style={{ all: "unset" }}
          >
            <div class="side-card">
              <img
                src={`/api/v2/blog/${blog.slug}/og-image?lang=${language}`}
                alt={blog.title}
              />

              <div class="side-card-content">
                <ElmInlineText bold>{blog.title}</ElmInlineText>

                <div class="side-card-content-description">
                  <ElmInlineText size="0.8rem">
                    {blog.description}
                  </ElmInlineText>
                </div>

                <Date createdAt={blog.created_at} updatedAt={blog.updated_at} />
              </div>

              <div class="side-card-tag-container">
                <ElmInlineText>TAG</ElmInlineText>
              </div>
            </div>
          </Link>
        ))}
      </>
    </nav>
  );
});

// src/components/blog/BlogSide.tsx
'use client'

import React from 'react'

import styles from './BlogSide.module.scss'

import Link from 'next/link'
import { Url } from 'next/dist/shared/lib/router/router'

// icons
import { ArrowPathIcon, CalendarDaysIcon } from '@heroicons/react/24/outline'

// relmethis
import { InlineText, Image } from 'relmethis'

// utils
import { type BlogMetadata } from '@/utils/blog/Markdown'

// # --------------------------------------------------------------------------------
//
// component
//
// # --------------------------------------------------------------------------------

interface BlogSideCardProps {
  href: Url
  image: string
  title: string
  description: string
  createdAt: string
  updatedAt: string
  index: number
}

const BlogSideCard = ({
  href,
  image,
  title,
  description,
  createdAt,
  updatedAt,
  index
}: BlogSideCardProps) => {
  return (
    <Link
      href={href}
      className={styles['side-card']}
      style={{ animationDelay: `${index * 200}ms` }}
    >
      <Image src={image} alt={title} />
      <div className={styles['side-card__typography']}>
        <div>
          <InlineText fontSize={'1.1rem'}>{title}</InlineText>
        </div>
        <div>
          <InlineText fontSize={'0.8rem'} opacity={0.6}>
            {description}
          </InlineText>
        </div>
        <div className={styles['side-card__date']}>
          <CalendarDaysIcon className={styles['side-card__icon']} />
          <InlineText fontSize={'0.8rem'} opacity={0.6}>
            {createdAt}
          </InlineText>
          <ArrowPathIcon className={styles['side-card__icon']} />
          <InlineText fontSize={'0.8rem'} opacity={0.7}>
            {updatedAt}
          </InlineText>
        </div>
      </div>
    </Link>
  )
}

interface BlogSideProps {
  blogMetadatas: BlogMetadata[]
}

export const BlogSide = ({ blogMetadatas }: BlogSideProps) => {
  return (
    <nav className={styles.side}>
      {blogMetadatas.map((meta, index) => (
        <BlogSideCard
          key={meta.slug}
          href={`/blog/article/${meta.slug}`}
          image={`/static/blog/${meta.slug}/ogp.webp`}
          title={meta.title}
          description={meta.description}
          createdAt={meta.createdAt}
          updatedAt={meta.updatedAt}
          index={index + 1}
        />
      ))}
    </nav>
  )
}
